/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MeloPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  displayLabelType: "path",
  showTags: false,
  hoverEffectType: "subtle",
  panelColor: "",
  alwaysShowLabels: false,
  defaultProfilePath: "",
  mapsFolder: "Melo Maps",
  enableHUD: true,
  defaultHoverLabelStyle: "default"
};
var SORT_LABELS = {
  "name-az": "File name (A to Z)",
  "name-za": "File name (Z to A)",
  "mtime-new": "Modified time (new to old)",
  "mtime-old": "Modified time (old to new)",
  "ctime-new": "Created time (new to old)",
  "ctime-old": "Created time (old to new)"
};
var VIEW_TYPE = "melo-view";
var PROFILE_TAG = "melo-profile";

// src/MeloView.ts
var import_obsidian4 = require("obsidian");

// src/ProfileManager.ts
var import_obsidian = require("obsidian");
var ProfileManager = class {
  constructor(app, plugin) {
    this.app = app;
    this.plugin = plugin;
  }
  /**
   * Retrieves all Markdown files in the vault that are marked as Melo Profiles.
   * Checks for the 'melo-profile: true' frontmatter property.
   * @returns Array of TFile objects.
   */
  getProfileFiles() {
    return this.app.vault.getMarkdownFiles().filter((f) => {
      const cache = this.app.metadataCache.getFileCache(f);
      return (cache == null ? void 0 : cache.frontmatter) && cache.frontmatter[PROFILE_TAG] === true;
    });
  }
  /**
   * Ensures that a folder exists in the vault, creating it if necessary.
   * @param folderPath The path to the folder.
   */
  async ensureFolderExists(folderPath) {
    if (!this.app.vault.getAbstractFileByPath(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
  }
  /**
   * Creates a new Melo Profile file.
   * @param name The name of the profile (filename).
   * @param imagePath The path to the background image.
   * @returns The created TFile.
   */
  async createProfile(name, imagePath) {
    const folder = this.plugin.settings.mapsFolder || "Melo Maps";
    await this.ensureFolderExists(folder);
    let filename = `${folder}/${name}.md`;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(filename)) {
      filename = `${folder}/${name} (${counter}).md`;
      counter++;
    }
    const frontmatter = {
      [PROFILE_TAG]: true,
      "image-path": imagePath,
      "hover-label-style": this.plugin.settings.defaultHoverLabelStyle || "default",
      "hotspots": []
    };
    const content = `---
${(0, import_obsidian.stringifyYaml)(frontmatter)}---
# ${name}
`;
    return await this.app.vault.create(filename, content);
  }
  /**
   * Updates the hotspots data in a profile file's frontmatter.
   * @param file The profile file to update.
   * @param hotspots The array of Hotspot objects to save.
   */
  async updateHotspots(file, hotspots) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const cleanHotspots = hotspots.map((h) => {
        const { isNew, ...rest } = h;
        return rest;
      });
      fm["hotspots"] = cleanHotspots;
    });
  }
  /**
   * Updates the hover label style for a specific profile.
   * @param file The profile file to update.
   * @param style The new style string.
   */
  async updateProfileStyle(file, style) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm["hover-label-style"] = style;
    });
  }
};

// src/utils.ts
function getAllTags(app, file) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  if (!cache) return [];
  let tags = [];
  if (cache.tags) tags = cache.tags.map((x) => x.tag);
  if ((_a = cache.frontmatter) == null ? void 0 : _a.tags) {
    const fmTags = cache.frontmatter.tags;
    if (Array.isArray(fmTags)) tags.push(...fmTags);
    else if (typeof fmTags === "string") tags.push(...fmTags.split(",").map((s) => s.trim()));
  }
  return [...new Set(tags)];
}
function smoothPath(pts) {
  const n = pts.length;
  if (n < 3) return pts.map((p, i) => `${i ? "L" : "M"} ${p[0]},${p[1]}`).join(" ") + " Z";
  let d = `M ${pts[0][0]},${pts[0][1]}`;
  const k = 0.33;
  for (let i = 0; i < n; i++) {
    const p0 = pts[(i - 1 + n) % n];
    const p1 = pts[i];
    const p2 = pts[(i + 1) % n];
    const p3 = pts[(i + 2) % n];
    const cp1x = p1[0] + (p2[0] - p0[0]) * k;
    const cp1y = p1[1] + (p2[1] - p0[1]) * k;
    const cp2x = p2[0] - (p3[0] - p1[0]) * k;
    const cp2y = p2[1] - (p3[1] - p1[1]) * k;
    d += ` C ${cp1x},${cp1y} ${cp2x},${cp2y} ${p2[0]},${p2[1]}`;
  }
  return d + " Z";
}
function centroid(pts) {
  if (!pts.length) return [50, 50];
  const sumX = pts.reduce((s, p) => s + p[0], 0);
  const sumY = pts.reduce((s, p) => s + p[1], 0);
  return [sumX / pts.length, sumY / pts.length];
}
function rotatePoints(pts, center, angleDegrees, aspectRatio) {
  const angleRad = angleDegrees * (Math.PI / 180);
  const cos = Math.cos(angleRad);
  const sin = Math.sin(angleRad);
  const [cx, cy] = center;
  return pts.map(([x, y]) => {
    const dx = (x - cx) * aspectRatio;
    const dy = y - cy;
    const nx = dx * cos - dy * sin;
    const ny = dx * sin + dy * cos;
    return [nx / aspectRatio + cx, ny + cy];
  });
}
function pct(e, img) {
  const rect = img.getBoundingClientRect();
  const x = Math.max(0, Math.min(100, (e.clientX - rect.left) / rect.width * 100));
  const y = Math.max(0, Math.min(100, (e.clientY - rect.top) / rect.height * 100));
  return [x, y];
}
function toClipPath(pts) {
  return "polygon(" + pts.map((p) => `${p[0]}% ${p[1]}%`).join(", ") + ")";
}
function confirmModal(title, onOk) {
  const modal = document.body.createDiv({ cls: "confirm-modal" });
  modal.createEl("h3", { text: title });
  const btnContainer = modal.createDiv({ cls: "modal-btns" });
  btnContainer.createEl("button", { text: "Cancel" }).onclick = () => modal.remove();
  btnContainer.createEl("button", { text: "Confirm", cls: "mod-warning" }).onclick = () => {
    onOk();
    modal.remove();
  };
}

// src/Modals.ts
var import_obsidian3 = require("obsidian");

// src/PathSuggest.ts
var import_obsidian2 = require("obsidian");
var PathSuggest = class {
  /**
   * @param app Obsidian App instance.
   * @param input The HTML input element to attach the suggester to.
   * @param exts Optional array of file extensions to filter by (e.g. ['png', 'jpg']).
   */
  constructor(app, input, exts = null) {
    this.box = null;
    this.items = [];
    this.idx = 0;
    this.app = app;
    this.input = input;
    this.exts = exts;
    input.addEventListener("input", () => this.update());
    input.addEventListener("keydown", (e) => this.key(e));
    input.addEventListener("blur", () => setTimeout(() => this.close(), 200));
  }
  /**
   * Updates the suggestion list based on current input value.
   */
  update() {
    const q = this.input.value.toLowerCase();
    this.items = this.app.vault.getAllLoadedFiles().filter((f) => {
      if (!f.path.toLowerCase().includes(q)) return false;
      if (this.exts && f instanceof import_obsidian2.TFile) return this.exts.includes(f.extension.toLowerCase());
      return true;
    }).sort((a, b) => {
      const aIsFolder = a instanceof import_obsidian2.TFolder ? 0 : 1;
      const bIsFolder = b instanceof import_obsidian2.TFolder ? 0 : 1;
      if (aIsFolder !== bIsFolder) return aIsFolder - bIsFolder;
      return a.path.localeCompare(b.path);
    }).slice(0, 10).map((f) => ({ label: f.path, type: f instanceof import_obsidian2.TFolder ? "folder" : "file" }));
    this.show();
  }
  /**
   * Renders the suggestion dropdown box.
   */
  show() {
    if (!this.items.length) {
      this.close();
      return;
    }
    if (!this.box) this.box = document.body.createDiv({ cls: "path-suggestion-container" });
    const r = this.input.getBoundingClientRect();
    this.box.style.cssText = `left:${r.left}px;top:${r.bottom + 4}px;width:${r.width}px;position:fixed;background:var(--background-primary);border:1px solid var(--background-modifier-border);border-radius:8px;box-shadow:0 4px 20px rgba(0,0,0,0.4);z-index:10000;max-height:200px;overflow-y:auto`;
    this.box.empty();
    this.idx = 0;
    this.items.forEach((it, i) => {
      const d = this.box.createDiv({ cls: "path-suggestion-item" + (i === this.idx ? " is-selected" : "") });
      d.createSpan({ text: (it.type === "folder" ? "\u{1F4C1} " : "\u{1F4C4} ") + it.label });
      d.onclick = () => {
        this.input.value = it.label;
        this.close();
        this.input.dispatchEvent(new Event("input"));
      };
    });
  }
  /**
   * Closes the suggestion box.
   */
  close() {
    var _a;
    (_a = this.box) == null ? void 0 : _a.remove();
    this.box = null;
  }
  /**
   * Handles keyboard navigation (Up/Down/Enter/Esc).
   */
  key(e) {
    if (!this.box) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      this.idx = (this.idx + 1) % this.items.length;
      this.show();
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      this.idx = (this.idx - 1 + this.items.length) % this.items.length;
      this.show();
    } else if (e.key === "Enter" && this.items[this.idx]) {
      e.preventDefault();
      this.input.value = this.items[this.idx].label;
      this.close();
    } else if (e.key === "Escape") {
      this.close();
    }
  }
};

// src/Modals.ts
var NewProfileModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, onSave) {
    super(app);
    this.plugin = plugin;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Create New Profile" });
    const container = contentEl.createDiv({ cls: "panel-file-list" });
    container.createEl("label", { text: "Name", attr: { style: "display:block;margin-bottom:5px;font-weight:bold" } });
    const nameInput = container.createEl("input", { attr: { type: "text" } });
    nameInput.style.cssText = "display:block;margin-bottom:15px;width:100%";
    container.createEl("label", { text: "Image Path", attr: { style: "display:block;margin-bottom:5px;font-weight:bold" } });
    const pathInput = container.createEl("input", { attr: { type: "text", placeholder: "e.g. assets/room.jpg" } });
    pathInput.style.cssText = "display:block;margin-bottom:20px;width:100%";
    new PathSuggest(this.app, pathInput, ["png", "jpg", "jpeg", "webp", "gif"]);
    const row = container.createDiv({ attr: { style: "display:flex;justify-content:flex-end;gap:10px" } });
    row.createEl("button", { text: "Create", cls: "mod-cta" }).onclick = async () => {
      if (!nameInput.value) return;
      const manager = new ProfileManager(this.app, this.plugin);
      const file = await manager.createProfile(nameInput.value, pathInput.value);
      this.onSave(file);
      this.close();
    };
    row.createEl("button", { text: "Cancel" }).onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImportProfileModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, onSave) {
    super(app);
    this.plugin = plugin;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Import Profile from Markdown" });
    const files = this.app.vault.getMarkdownFiles().filter((f) => {
      const c = this.app.metadataCache.getFileCache(f);
      return (c == null ? void 0 : c.frontmatter) && c.frontmatter["image-map-profile"] === true;
    });
    if (files.length === 0) {
      contentEl.createDiv({ text: 'No profile files found in vault. (Files must have "image-map-profile: true" in frontmatter)', attr: { style: "color:var(--text-muted);font-style:italic" } });
      return;
    }
    const list = contentEl.createDiv({ cls: "import-file-list" });
    list.style.cssText = "max-height:300px;overflow-y:auto;border:1px solid var(--background-modifier-border);border-radius:4px;margin-bottom:20px";
    files.forEach((f) => {
      const item = list.createDiv({ cls: "import-item" });
      item.style.cssText = "padding:10px;border-bottom:1px solid var(--background-modifier-border);cursor:pointer;display:flex;justify-content:space-between;align-items:center";
      item.onmouseover = () => item.style.background = "var(--background-modifier-hover)";
      item.onmouseout = () => item.style.background = "transparent";
      const info = item.createDiv();
      info.createDiv({ text: f.basename, attr: { style: "font-weight:bold" } });
      info.createDiv({ text: f.path, attr: { style: "font-size:0.8em;color:var(--text-muted)" } });
      item.onclick = async () => {
        const c = this.app.metadataCache.getFileCache(f);
        if (c == null ? void 0 : c.frontmatter) {
          new import_obsidian3.Notice(`Profile "${f.basename}" is ready to use.`);
          this.onSave();
          this.close();
        }
      };
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var FilePreviewModal = class extends import_obsidian3.Modal {
  constructor(app, title, content, file) {
    super(app);
    this.title = title;
    this.content = content;
    this.file = file;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("melo-preview-modal");
    const header = contentEl.createDiv({ cls: "preview-header" });
    header.createEl("h2", { text: this.title });
    const openBtn = header.createEl("button", { text: "Open in New Tab", cls: "mod-cta" });
    openBtn.onclick = () => {
      this.app.workspace.getLeaf("tab").openFile(this.file);
      this.close();
    };
    const body = contentEl.createDiv({ cls: "markdown-preview-view" });
    import_obsidian3.MarkdownRenderer.render(this.app, this.content, body, "", new import_obsidian3.Component());
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/MeloView.ts
var MeloView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    // Current state
    this.currentFile = null;
    this.currentHotspots = [];
    this.currentImagePath = "";
    this.currentHoverStyle = "default";
    // Store current profile's style
    // Editing state
    this.editMode = false;
    this.selectedId = null;
    this.editingId = null;
    this.drawShape = null;
    this.undoStack = [];
    // Sorting state for file list
    this.sortType = "ctime-new";
    // Color sampling canvas
    this.colorCanvas = null;
    this.colorCtx = null;
    this.canvasSrc = "";
    // HUD element reference
    this.hudEl = null;
    this.plugin = plugin;
    this.manager = new ProfileManager(this.app, plugin);
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Melo View";
  }
  getIcon() {
    return "map";
  }
  async onOpen() {
    if (!this.currentFile && this.plugin.settings.defaultProfilePath) {
      const file = this.app.vault.getAbstractFileByPath(this.plugin.settings.defaultProfilePath);
      if (file instanceof import_obsidian4.TFile) {
        await this.loadProfile(file);
      }
    }
    this.render();
    this.registerDomEvent(document, "keydown", (e) => {
      if (!this.editingId) return;
      const h = this.currentHotspots.find((x) => x.id === this.editingId);
      if (!(h == null ? void 0 : h.points)) return;
      if (e.key === "z" && (e.ctrlKey || e.metaKey) && this.undoStack.length > 1) {
        e.preventDefault();
        this.undoStack.pop();
        h.points = this.undoStack[this.undoStack.length - 1].map((p) => [...p]);
        this.render();
      } else if (e.key === "Escape") {
        this.editingId = null;
        this.render();
      }
    });
  }
  /**
   * Loads a profile from a Markdown file.
   * Reads frontmatter for image path and hotspots data.
   */
  async loadProfile(file) {
    this.currentFile = file;
    const cache = this.app.metadataCache.getFileCache(file);
    if (cache == null ? void 0 : cache.frontmatter) {
      this.currentImagePath = cache.frontmatter["image-path"] || "";
      this.currentHotspots = cache.frontmatter["hotspots"] || [];
      this.currentHoverStyle = cache.frontmatter["hover-label-style"] || this.plugin.settings.defaultHoverLabelStyle || "default";
    }
    this.render();
  }
  /**
   * Saves the current hotspots to the profile file.
   */
  async saveCurrentProfile() {
    if (this.currentFile) {
      await this.manager.updateHotspots(this.currentFile, this.currentHotspots);
    }
  }
  // #region HUD Logic
  /**
   * Shows a Heads-Up Display (HUD) card with file details on hover.
   */
  async showHUD(e, h, anchor) {
    if (!this.plugin.settings.enableHUD || !h.path) return;
    this.hideHUD();
    const file = this.app.vault.getAbstractFileByPath(h.path.split("#")[0]);
    if (!(file instanceof import_obsidian4.TFile)) return;
    this.hudEl = document.body.createDiv({ cls: "melo-hud-card" });
    const rect = anchor.getBoundingClientRect();
    this.hudEl.style.left = `${rect.left + 20}px`;
    this.hudEl.style.top = `${rect.top}px`;
    const header = this.hudEl.createDiv({ cls: "hud-header" });
    header.createDiv({ cls: "hud-title", text: h.name || file.basename });
    const meta = this.hudEl.createDiv({ cls: "hud-meta" });
    meta.createSpan({ cls: "hud-date", text: (0, import_obsidian4.moment)(file.stat.mtime).format("YYYY-MM-DD") });
    const tags = getAllTags(this.app, file);
    if (tags.length > 0) {
      const tagContainer = this.hudEl.createDiv({ cls: "hud-tags" });
      tags.slice(0, 3).forEach((t) => tagContainer.createSpan({ cls: "hud-tag", text: t }));
      if (tags.length > 3) tagContainer.createSpan({ cls: "hud-tag", text: `+${tags.length - 3}` });
    }
    const contentDiv = this.hudEl.createDiv({ cls: "hud-content" });
    contentDiv.setText("Loading...");
    setTimeout(async () => {
      if (!this.hudEl) return;
      try {
        const content = await this.app.vault.cachedRead(file);
        const lines = content.split("\n").slice(0, 3).join("\n");
        contentDiv.empty();
        import_obsidian4.MarkdownRenderer.render(this.app, lines, contentDiv, "", new import_obsidian4.Component());
      } catch (err) {
        contentDiv.setText("Failed to load content");
      }
    }, 100);
  }
  hideHUD() {
    if (this.hudEl) {
      this.hudEl.remove();
      this.hudEl = null;
    }
  }
  // #endregion
  /**
   * Main render function. Rebuilds the entire view DOM.
   */
  render() {
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("melo-wrapper");
    const dash = root.createDiv({ cls: "melo-dashboard" });
    const tools = dash.createDiv({ cls: "melo-tools" });
    const tL = tools.createDiv({ cls: "toolbar-left" });
    const tR = tools.createDiv({ cls: "toolbar-right" });
    const selContainer = tL.createDiv({ attr: { style: "display:flex;gap:5px;align-items:center" } });
    const sel = selContainer.createEl("select", { cls: "profile-selector" });
    const files = this.manager.getProfileFiles();
    const filesByFolder = {};
    const mapsFolder = this.plugin.settings.mapsFolder || "Melo Maps";
    files.forEach((f) => {
      let parentPath = f.parent ? f.parent.path : "/";
      if (parentPath.startsWith(mapsFolder)) {
        parentPath = parentPath.substring(mapsFolder.length);
        if (parentPath.startsWith("/")) parentPath = parentPath.substring(1);
        if (parentPath === "") parentPath = "/";
      }
      if (!filesByFolder[parentPath]) filesByFolder[parentPath] = [];
      filesByFolder[parentPath].push(f);
    });
    const sortedFolders = Object.keys(filesByFolder).sort();
    sortedFolders.forEach((folderPath) => {
      const label = folderPath === "/" ? "Root" : folderPath;
      const group = sel.createEl("optgroup", { attr: { label } });
      filesByFolder[folderPath].sort((a, b) => a.basename.localeCompare(b.basename));
      filesByFolder[folderPath].forEach((f) => {
        const o = group.createEl("option", { text: f.basename, value: f.path });
        if (this.currentFile && f.path === this.currentFile.path) o.selected = true;
      });
    });
    sel.createEl("option", { text: "\u2795 Create New Map...", value: "__NEW__" });
    sel.onchange = async () => {
      if (sel.value === "__NEW__") {
        new NewProfileModal(this.app, this.plugin, async (file) => {
          await this.loadProfile(file);
          this.render();
        }).open();
        sel.value = "";
      } else if (sel.value) {
        const file = this.app.vault.getAbstractFileByPath(sel.value);
        if (file instanceof import_obsidian4.TFile) await this.loadProfile(file);
      } else {
        this.currentFile = null;
        this.render();
      }
    };
    if (this.currentFile) {
      selContainer.createEl("button", { text: "Edit", attr: { title: "Open File" } }).onclick = () => {
        if (this.currentFile) this.app.workspace.getLeaf("tab").openFile(this.currentFile);
      };
      const labelBtn = selContainer.createEl("button", {
        text: this.plugin.settings.alwaysShowLabels ? "Hide Labels" : "Show Labels",
        attr: { title: "Toggle Always Show Labels" }
      });
      labelBtn.onclick = async () => {
        this.plugin.settings.alwaysShowLabels = !this.plugin.settings.alwaysShowLabels;
        await this.plugin.saveSettings();
        this.render();
      };
      const styleSel = selContainer.createEl("select", { cls: "style-selector" });
      styleSel.style.maxWidth = "120px";
      const styles = [
        { v: "default", l: "Default" },
        { v: "glass", l: "Glass" },
        { v: "neon", l: "Neon" },
        { v: "minimal", l: "Minimal" },
        { v: "comic", l: "Comic" },
        { v: "scale", l: "Scale" },
        { v: "fantasy", l: "Fantasy" }
      ];
      styles.forEach((s) => {
        const o = styleSel.createEl("option", { text: s.l, value: s.v });
        if (s.v === this.currentHoverStyle) o.selected = true;
      });
      styleSel.onchange = async () => {
        this.currentHoverStyle = styleSel.value;
        if (this.currentFile) {
          await this.manager.updateProfileStyle(this.currentFile, this.currentHoverStyle);
        }
        this.render();
      };
    }
    if (this.currentFile) {
      if (!this.editMode) {
        tR.createEl("button", { text: "\u270F\uFE0F Edit Map", cls: "mod-cta" }).onclick = () => {
          this.editMode = true;
          this.selectedId = null;
          this.render();
        };
      } else {
        const st = tR.createDiv({ attr: { style: "margin-right:10px;display:flex;gap:5px" } });
        const shapeBtn = st.createEl("button", { text: "Shapes \u25BE" });
        shapeBtn.onclick = (e) => {
          const menu = new import_obsidian4.Menu();
          const shapes = [
            { type: "rect", icon: "\u2B1A", label: "Rectangle" },
            { type: "ellipse", icon: "\u25EF", label: "Circle" },
            { type: "triangle", icon: "\u25B3", label: "Triangle" },
            { type: "arrow", icon: "\u279C", label: "Arrow" },
            { type: "bubble", icon: "\u{1F5E8}", label: "Speech Bubble" }
          ];
          shapes.forEach((s) => {
            menu.addItem((item) => {
              item.setTitle(s.icon + " " + s.label).onClick(() => {
                this.drawShape = s.type;
                this.selectedId = null;
                this.render();
              });
              if (this.drawShape === s.type) item.setChecked(true);
            });
          });
          menu.showAtMouseEvent(e);
        };
        if (this.drawShape) shapeBtn.addClass("is-active");
        st.createEl("button", { text: "\u2705 Done", cls: "btn-done" }).onclick = async () => {
          this.editMode = false;
          this.drawShape = null;
          this.editingId = null;
          this.selectedId = null;
          await this.saveCurrentProfile();
          this.render();
        };
      }
    }
    if (!this.currentFile) {
      dash.createEl("h3", { text: "Select or create a map to get started." });
      return;
    }
    const dir = this.plugin.manifest.dir || ".";
    const imgPath = this.currentImagePath || "";
    let src;
    if (imgPath.startsWith("http://") || imgPath.startsWith("https://")) {
      src = imgPath;
    } else {
      const af = this.app.vault.getAbstractFileByPath(imgPath);
      src = af instanceof import_obsidian4.TFile ? this.app.vault.getResourcePath(af) : this.app.vault.adapter.getResourcePath(dir + "/" + (imgPath || "room-bg.png"));
    }
    const box = dash.createDiv({ cls: "melo-image-container" });
    if (this.plugin.settings.alwaysShowLabels) {
      box.addClass("always-show-labels");
    }
    const img = box.createEl("img", { cls: "melo-bg-img", attr: { src, draggable: "false" } });
    if (src !== this.canvasSrc) {
      img.onload = () => {
        try {
          const c = document.createElement("canvas");
          c.width = img.naturalWidth;
          c.height = img.naturalHeight;
          const ctx = c.getContext("2d", { willReadFrequently: true });
          if (ctx) {
            ctx.drawImage(img, 0, 0);
            this.colorCanvas = c;
            this.colorCtx = ctx;
            this.canvasSrc = src;
          }
        } catch (_) {
        }
      };
    }
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("viewBox", "0 0 100 100");
    svg.setAttribute("preserveAspectRatio", "none");
    svg.classList.add("melo-svg-layer");
    box.appendChild(svg);
    const ov = box.createDiv({ cls: "melo-overlay" });
    if (this.editMode && this.drawShape) {
      box.style.cursor = "crosshair";
      const dSvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      dSvg.setAttribute("viewBox", "0 0 100 100");
      dSvg.setAttribute("preserveAspectRatio", "none");
      dSvg.classList.add("drawing-svg-layer");
      box.appendChild(dSvg);
      let dragging = false, sx = 0, sy = 0;
      let preview = null;
      const shapeType = this.drawShape;
      const onDown = (e) => {
        if (e.button !== 0) return;
        const rect = img.getBoundingClientRect();
        if (e.clientX < rect.left || e.clientX > rect.right || e.clientY < rect.top || e.clientY > rect.bottom) return;
        e.preventDefault();
        dragging = true;
        [sx, sy] = pct(e, img);
        const tag = shapeType === "rect" ? "rect" : shapeType === "ellipse" ? "ellipse" : "polygon";
        preview = document.createElementNS("http://www.w3.org/2000/svg", tag);
        preview.setAttribute("vector-effect", "non-scaling-stroke");
        preview.style.cssText = "stroke:#2196f3;stroke-width:2;fill:rgba(33,150,243,0.25)";
        if (tag === "polygon") {
          preview.setAttribute("points", `${sx},${sy} ${sx},${sy} ${sx},${sy}`);
        } else if (tag === "rect") {
          preview.setAttribute("x", String(sx));
          preview.setAttribute("y", String(sy));
          preview.setAttribute("width", "0");
          preview.setAttribute("height", "0");
        } else if (tag === "ellipse") {
          preview.setAttribute("cx", String(sx));
          preview.setAttribute("cy", String(sy));
          preview.setAttribute("rx", "0");
          preview.setAttribute("ry", "0");
        }
        dSvg.appendChild(preview);
      };
      const onMove = (e) => {
        if (!dragging || !preview) return;
        e.preventDefault();
        const [cx, cy] = pct(e, img);
        const x1 = Math.min(sx, cx), y1 = Math.min(sy, cy);
        const w = Math.abs(cx - sx), h = Math.abs(cy - sy);
        const x2 = Math.max(sx, cx);
        const y2 = Math.max(sy, cy);
        const isRight = cx >= sx;
        const isDown = cy >= sy;
        if (shapeType === "rect") {
          preview.setAttribute("x", String(x1));
          preview.setAttribute("y", String(y1));
          preview.setAttribute("width", String(w));
          preview.setAttribute("height", String(h));
        } else if (shapeType === "ellipse") {
          preview.setAttribute("cx", String(x1 + w / 2));
          preview.setAttribute("cy", String(y1 + h / 2));
          preview.setAttribute("rx", String(w / 2));
          preview.setAttribute("ry", String(h / 2));
        } else if (shapeType === "arrow") {
          const ax1 = sx, ay1 = sy, ax2 = cx, ay2 = cy;
          const aw = Math.abs(ax2 - ax1), ah = Math.abs(ay2 - ay1);
          let pts = [];
          if (aw > ah) {
            const my = ay1 + (ay2 - ay1) / 2;
            const tailThick = Math.min(ah * 0.4, aw * 0.3);
            const headBack = isRight ? ax2 - Math.min(aw * 0.4, ah) : ax2 + Math.min(aw * 0.4, ah);
            pts = [
              [ax1, ay1 + (ah - tailThick) / 2],
              // Tail top-left
              [headBack, ay1 + (ah - tailThick) / 2],
              // Head back top
              [headBack, ay1],
              // Head top wing
              [ax2, my],
              // Tip
              [headBack, ay2],
              // Head bottom wing
              [headBack, ay2 - (ah - tailThick) / 2],
              // Head back bottom
              [ax1, ay2 - (ah - tailThick) / 2]
              // Tail bottom-left
            ];
          } else {
            const mx = ax1 + (ax2 - ax1) / 2;
            const tailThick = Math.min(aw * 0.4, ah * 0.3);
            const headBack = isDown ? ay2 - Math.min(ah * 0.4, aw) : ay2 + Math.min(ah * 0.4, aw);
            pts = [
              [ax1 + (aw - tailThick) / 2, ay1],
              // Tail top-left
              [ax1 + (aw - tailThick) / 2, headBack],
              // Tail bottom-left (at head)
              [ax1, headBack],
              // Head left wing
              [mx, ay2],
              // Tip
              [ax2, headBack],
              // Head right wing
              [ax2 - (aw - tailThick) / 2, headBack],
              // Tail bottom-right (at head)
              [ax2 - (aw - tailThick) / 2, ay1]
              // Tail top-right
            ];
          }
          preview.setAttribute("points", pts.map((p) => `${p[0]},${p[1]}`).join(" "));
        } else if (shapeType === "bubble") {
          const tailH = h * 0.3;
          const tailW = w * 0.2;
          const bodyH = h - tailH;
          const pts = [
            [x1, y1],
            [x2, y1],
            [x2, y1 + bodyH],
            [x1 + w * 0.5 + tailW, y1 + bodyH],
            [x1 + w * 0.5, y2],
            // Tail tip
            [x1 + w * 0.5 - tailW, y1 + bodyH],
            [x1, y1 + bodyH]
          ];
          preview.setAttribute("points", pts.map((p) => `${p[0]},${p[1]}`).join(" "));
        } else {
          preview.setAttribute("points", `${x1 + w / 2},${y1} ${x1},${y1 + h} ${x1 + w},${y1 + h}`);
        }
      };
      const onUp = async (e) => {
        if (!dragging) return;
        dragging = false;
        document.removeEventListener("mousemove", onMove);
        document.removeEventListener("mouseup", onUp);
        const [cx, cy] = pct(e, img);
        const x1 = Math.min(sx, cx), x2 = Math.max(sx, cx), y1 = Math.min(sy, cy), y2 = Math.max(sy, cy);
        const w = x2 - x1, h = y2 - y1;
        const isRight = cx >= sx;
        const isDown = cy >= sy;
        if (w < 1 && h < 1) {
          preview == null ? void 0 : preview.remove();
          return;
        }
        let pts;
        if (shapeType === "rect") {
          pts = [[x1, y1], [x2, y1], [x2, y2], [x1, y2]];
        } else if (shapeType === "ellipse") {
          pts = [];
          const cr = x1 + w / 2, cc = y1 + h / 2, rx = w / 2, ry = h / 2;
          for (let i = 0; i < 16; i++) {
            const a = Math.PI * 2 * i / 16;
            pts.push([cr + rx * Math.cos(a), cc + ry * Math.sin(a)]);
          }
        } else if (shapeType === "triangle") {
          pts = [[x1 + w / 2, y1], [x1, y2], [x2, y2]];
        } else if (shapeType === "arrow") {
          const ax1 = sx, ay1 = sy, ax2 = cx, ay2 = cy;
          const aw = Math.abs(ax2 - ax1), ah = Math.abs(ay2 - ay1);
          if (aw > ah) {
            const my = ay1 + (ay2 - ay1) / 2;
            const tailThick = Math.min(ah * 0.4, aw * 0.3);
            const headBack = isRight ? ax2 - Math.min(aw * 0.4, ah) : ax2 + Math.min(aw * 0.4, ah);
            pts = [
              [ax1, ay1 + (ah - tailThick) / 2],
              [headBack, ay1 + (ah - tailThick) / 2],
              [headBack, ay1],
              [ax2, my],
              [headBack, ay2],
              [headBack, ay2 - (ah - tailThick) / 2],
              [ax1, ay2 - (ah - tailThick) / 2]
            ];
          } else {
            const mx = ax1 + (ax2 - ax1) / 2;
            const tailThick = Math.min(aw * 0.4, ah * 0.3);
            const headBack = isDown ? ay2 - Math.min(ah * 0.4, aw) : ay2 + Math.min(ah * 0.4, aw);
            pts = [
              [ax1 + (aw - tailThick) / 2, ay1],
              [ax1 + (aw - tailThick) / 2, headBack],
              [ax1, headBack],
              [mx, ay2],
              [ax2, headBack],
              [ax2 - (aw - tailThick) / 2, headBack],
              [ax2 - (aw - tailThick) / 2, ay1]
            ];
          }
        } else if (shapeType === "bubble") {
          const tailH = h * 0.3;
          const tailW = w * 0.2;
          const bodyH = h - tailH;
          pts = [
            [x1, y1],
            [x2, y1],
            [x2, y1 + bodyH],
            [x1 + w * 0.5 + tailW, y1 + bodyH],
            [x1 + w * 0.5, y2],
            // Tail tip
            [x1 + w * 0.5 - tailW, y1 + bodyH],
            [x1, y1 + bodyH]
          ];
        } else {
          pts = [[x1, y1], [x2, y1], [x2, y2], [x1, y2]];
        }
        const nh = {
          id: Date.now().toString(),
          name: "",
          path: "",
          points: pts,
          shapeType,
          isNew: true
          // Mark as new for immediate editing
        };
        this.currentHotspots.push(nh);
        this.editingId = nh.id;
        this.drawShape = null;
        this.render();
        await this.saveCurrentProfile();
      };
      box.addEventListener("mousedown", onDown);
      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onUp);
    }
    this.currentHotspots.forEach((h) => {
      var _a;
      if (!((_a = h.points) == null ? void 0 : _a.length)) return;
      const editing = this.editingId === h.id;
      const selected = this.selectedId === h.id;
      const isEllipse = h.shapeType === "ellipse" || h.shapeType === "bubble";
      const el = document.createElementNS("http://www.w3.org/2000/svg", isEllipse ? "path" : "polygon");
      el.classList.add("hotspot-shape");
      el.setAttribute("vector-effect", "non-scaling-stroke");
      if (isEllipse) el.setAttribute("d", smoothPath(h.points));
      else el.setAttribute("points", h.points.map((p) => `${p[0]},${p[1]}`).join(" "));
      if (editing) {
        el.style.cssText = "fill:rgba(76,175,80,0.3);stroke:#4caf50;stroke-width:1.5";
      } else if (selected) {
        el.style.cssText = "fill:rgba(33,150,243,0.3);stroke:#2196f3;stroke-width:1.5";
      } else if (this.editMode) {
        el.style.cssText = "fill:rgba(255,255,255,0.15);stroke:rgba(255,255,255,0.35);stroke-width:1";
      } else {
        el.style.cssText = `fill:${h.color ? h.color + "40" : "rgba(255,255,255,0.01)"};stroke:${h.color || "transparent"};stroke-width:${h.color ? "1" : "0"}`;
      }
      svg.appendChild(el);
      const [cx, cy] = centroid(h.points);
      const anchor = ov.createDiv({ cls: "hotspot-anchor" });
      anchor.style.cssText = `left:${cx}%;top:${cy}%`;
      let txt = h.name || "Region";
      const lt = this.plugin.settings.displayLabelType;
      if (lt === "path" && h.path) {
        const [fp, sec] = h.path.split("#", 2);
        const fname = fp.split("/").pop() || "";
        txt = sec ? sec : fname.replace(/\.[^.]+$/, "");
      } else if (lt === "both") {
        const [fp, sec] = (h.path || "").split("#", 2);
        const fname = fp.split("/").pop() || "?";
        const short = sec ? sec : fname.replace(/\.[^.]+$/, "");
        txt = `${h.name || "Region"} (${short})`;
      }
      if (!editing) {
        const labelEl = anchor.createDiv({ cls: "hotspot-label", text: txt });
        labelEl.addClass(`style-${this.currentHoverStyle}`);
      }
      if (editing) {
        h.points.forEach((pt, idx) => {
          const handle = ov.createDiv({ cls: "vertex-handle" });
          handle.style.cssText = `left:${pt[0]}%;top:${pt[1]}%`;
          handle.addEventListener("mousedown", (e) => {
            e.stopPropagation();
            e.preventDefault();
            this.undoStack.push(h.points.map((p) => [...p]));
            const onMove = (mv) => {
              mv.preventDefault();
              const [nx, ny] = pct(mv, img);
              h.points[idx] = [nx, ny];
              if (isEllipse) el.setAttribute("d", smoothPath(h.points));
              else el.setAttribute("points", h.points.map((p) => `${p[0]},${p[1]}`).join(" "));
              handle.style.left = `${nx}%`;
              handle.style.top = `${ny}%`;
              const [ncx, ncy] = centroid(h.points);
              anchor.style.left = `${ncx}%`;
              anchor.style.top = `${ncy}%`;
              const moveHandle2 = ov.querySelector(".move-handle");
              if (moveHandle2) {
                moveHandle2.style.left = `${ncx}%`;
                moveHandle2.style.top = `${ncy}%`;
              }
              const rotateHandle2 = ov.querySelector(".rotate-handle");
              if (rotateHandle2) {
                const minY2 = Math.min(...h.points.map((p) => p[1]));
                rotateHandle2.style.left = `${ncx}%`;
                rotateHandle2.style.top = `${minY2 - 5}%`;
              }
              const btns2 = ov.querySelector(".edge-edit-btns");
              if (btns2) {
                btns2.style.top = `${Math.max(...h.points.map((p) => p[1])) + 2}%`;
                btns2.style.left = `${ncx}%`;
              }
            };
            const onUp = () => {
              document.removeEventListener("mousemove", onMove);
              document.removeEventListener("mouseup", onUp);
              this.saveCurrentProfile();
            };
            document.addEventListener("mousemove", onMove);
            document.addEventListener("mouseup", onUp);
          });
        });
        const moveHandle = ov.createDiv({ cls: "move-handle" });
        moveHandle.style.cssText = `left:${cx}%;top:${cy}%`;
        moveHandle.addEventListener("mousedown", (e) => {
          e.stopPropagation();
          e.preventDefault();
          this.undoStack.push(h.points.map((p) => [...p]));
          const [startX, startY] = pct(e, img);
          const initialPoints = h.points.map((p) => [...p]);
          const onMove = (mv) => {
            mv.preventDefault();
            const [currX, currY] = pct(mv, img);
            const dx = currX - startX;
            const dy = currY - startY;
            h.points = initialPoints.map((p) => [p[0] + dx, p[1] + dy]);
            if (isEllipse) el.setAttribute("d", smoothPath(h.points));
            else el.setAttribute("points", h.points.map((p) => `${p[0]},${p[1]}`).join(" "));
            const [ncx, ncy] = centroid(h.points);
            moveHandle.style.left = `${ncx}%`;
            moveHandle.style.top = `${ncy}%`;
            const handles = ov.querySelectorAll(".vertex-handle");
            h.points.forEach((p, i) => {
              if (handles[i]) {
                handles[i].style.left = `${p[0]}%`;
                handles[i].style.top = `${p[1]}%`;
              }
            });
            const rotateHandle2 = ov.querySelector(".rotate-handle");
            if (rotateHandle2) {
              const minY2 = Math.min(...h.points.map((p) => p[1]));
              rotateHandle2.style.left = `${ncx}%`;
              rotateHandle2.style.top = `${minY2 - 5}%`;
            }
            const btns2 = ov.querySelector(".edge-edit-btns");
            if (btns2) {
              btns2.style.top = `${Math.max(...h.points.map((p) => p[1])) + 2}%`;
              btns2.style.left = `${ncx}%`;
            }
          };
          const onUp = () => {
            document.removeEventListener("mousemove", onMove);
            document.removeEventListener("mouseup", onUp);
            this.saveCurrentProfile();
          };
          document.addEventListener("mousemove", onMove);
          document.addEventListener("mouseup", onUp);
        });
        const minY = Math.min(...h.points.map((p) => p[1]));
        const rotateHandle = ov.createDiv({ cls: "rotate-handle" });
        rotateHandle.style.cssText = `left:${cx}%;top:${minY - 5}%`;
        rotateHandle.addEventListener("mousedown", (e) => {
          e.stopPropagation();
          e.preventDefault();
          this.undoStack.push(h.points.map((p) => [...p]));
          const center = centroid(h.points);
          const rect = img.getBoundingClientRect();
          const centerX = rect.left + center[0] / 100 * rect.width;
          const centerY = rect.top + center[1] / 100 * rect.height;
          let lastAngle = Math.atan2(e.clientY - centerY, e.clientX - centerX);
          const onMove = (mv) => {
            mv.preventDefault();
            const currAngle = Math.atan2(mv.clientY - centerY, mv.clientX - centerX);
            const deltaAngle = (currAngle - lastAngle) * (180 / Math.PI);
            lastAngle = currAngle;
            const aspectRatio = img.width / img.height;
            h.points = rotatePoints(h.points, center, deltaAngle, aspectRatio);
            if (isEllipse) el.setAttribute("d", smoothPath(h.points));
            else el.setAttribute("points", h.points.map((p) => `${p[0]},${p[1]}`).join(" "));
            const handles = ov.querySelectorAll(".vertex-handle");
            h.points.forEach((p, i) => {
              if (handles[i]) {
                handles[i].style.left = `${p[0]}%`;
                handles[i].style.top = `${p[1]}%`;
              }
            });
            const newMinY = Math.min(...h.points.map((p) => p[1]));
            const [ncx, ncy] = centroid(h.points);
            rotateHandle.style.left = `${ncx}%`;
            rotateHandle.style.top = `${newMinY - 5}%`;
            const btns2 = ov.querySelector(".edge-edit-btns");
            if (btns2) {
              btns2.style.top = `${Math.max(...h.points.map((p) => p[1])) + 2}%`;
              btns2.style.left = `${ncx}%`;
            }
          };
          const onUp = () => {
            document.removeEventListener("mousemove", onMove);
            document.removeEventListener("mouseup", onUp);
            this.saveCurrentProfile();
          };
          document.addEventListener("mousemove", onMove);
          document.addEventListener("mouseup", onUp);
        });
        const maxY = Math.max(...h.points.map((p) => p[1]));
        const btns = ov.createDiv({ cls: "edge-edit-btns" });
        btns.style.cssText = `position:absolute;top:${maxY + 2}%;left:${cx}%;transform:translateX(-50%);z-index:2000;display:flex;gap:5px;`;
        btns.createEl("button", { text: "\u2705", cls: "btn-confirm-icon" }).onclick = () => {
          this.editingId = null;
          if (h.isNew) {
            delete h.isNew;
            this.saveCurrentProfile();
          }
          if (!h.name) this.regionModal(h);
          else this.render();
        };
        btns.createEl("button", { text: "\u{1F5D1}\uFE0F", cls: "btn-delete-icon" }).onclick = () => {
          if (h.isNew) {
            this.currentHotspots.splice(this.currentHotspots.indexOf(h), 1);
            this.editingId = null;
            this.saveCurrentProfile();
            this.render();
          } else {
            confirmModal("Delete this region?", () => {
              this.currentHotspots.splice(this.currentHotspots.indexOf(h), 1);
              this.editingId = null;
              this.saveCurrentProfile();
              this.render();
            });
          }
        };
      } else {
        const hitArea = ov.createDiv({ cls: "hotspot-hitarea" });
        hitArea.style.cssText = `position:absolute;top:0;left:0;width:100%;height:100%;clip-path:${toClipPath(h.points)};-webkit-clip-path:${toClipPath(h.points)};pointer-events:auto;cursor:pointer;z-index:1`;
        let wasDragging = false;
        hitArea.addEventListener("click", async (e) => {
          e.stopPropagation();
          if (wasDragging) {
            wasDragging = false;
            return;
          }
          if (this.editMode) {
            this.selectedId = h.id;
            this.render();
            const menu = new import_obsidian4.Menu();
            menu.addItem((i) => i.setTitle("\u270F\uFE0F Edit Edges").onClick(() => {
              this.editingId = h.id;
              this.render();
            }));
            menu.addItem((i) => i.setTitle("\u{1F517} Edit Link").onClick(() => this.regionModal(h)));
            menu.addItem((i) => i.setTitle("\u{1F5D1}\uFE0F Delete").onClick(() => confirmModal("Delete?", () => {
              this.currentHotspots.splice(this.currentHotspots.indexOf(h), 1);
              this.saveCurrentProfile();
              this.render();
            })));
            menu.showAtMouseEvent(e);
          } else {
            if (h.embed && h.path) {
              const file2 = this.app.vault.getAbstractFileByPath(h.path.split("#")[0]);
              if (file2 instanceof import_obsidian4.TFile) {
                const content = await this.readSubpathContent(file2, h.path);
                new FilePreviewModal(this.app, h.name || file2.basename, content, file2).open();
                return;
              }
            }
            const file = this.app.vault.getAbstractFileByPath(h.path.split("#")[0]);
            if (file instanceof import_obsidian4.TFile) {
              const cache = this.app.metadataCache.getFileCache(file);
              if ((cache == null ? void 0 : cache.frontmatter) && cache.frontmatter[PROFILE_TAG] === true) {
                this.loadProfile(file);
                return;
              }
            }
            this.showFiles(h);
          }
        });
        hitArea.addEventListener("mouseenter", (e) => {
          if (this.editMode) return;
          const hv = this.plugin.settings.hoverEffectType;
          if (hv === "subtle") el.style.fill = "rgba(255,255,255,0.10)";
          else if (hv === "high") el.style.fill = "rgba(255,255,255,0.28)";
          if (this.plugin.settings.alwaysShowLabels) {
            anchor.addClass("is-hovered");
          }
          anchor.addClass("is-active");
          this.showHUD(e, h, anchor);
        });
        hitArea.addEventListener("mouseleave", () => {
          if (this.editMode) return;
          el.style.fill = h.color ? h.color + "40" : "rgba(255,255,255,0.01)";
          if (this.plugin.settings.alwaysShowLabels) {
            anchor.removeClass("is-hovered");
          }
          anchor.removeClass("is-active");
          this.hideHUD();
        });
        if (this.editMode && selected && !editing) {
          let isDraggingRegion = false;
          let startX, startY;
          let initialPoints;
          hitArea.addEventListener("mousedown", (e) => {
            if (e.button !== 0) return;
            e.stopPropagation();
            e.preventDefault();
            isDraggingRegion = true;
            wasDragging = false;
            [startX, startY] = pct(e, img);
            initialPoints = h.points.map((p) => [...p]);
            this.undoStack.push(h.points.map((p) => [...p]));
            const onMouseMove = (mv) => {
              if (!isDraggingRegion) return;
              mv.preventDefault();
              wasDragging = true;
              const [currentX, currentY] = pct(mv, img);
              const deltaX = currentX - startX;
              const deltaY = currentY - startY;
              const newPoints = initialPoints.map((p) => [p[0] + deltaX, p[1] + deltaY]);
              h.points = newPoints;
              if (isEllipse) el.setAttribute("d", smoothPath(h.points));
              else el.setAttribute("points", h.points.map((p) => `${p[0]},${p[1]}`).join(" "));
              const [ncx, ncy] = centroid(h.points);
              anchor.style.left = `${ncx}%`;
              anchor.style.top = `${ncy}%`;
              hitArea.style.clipPath = toClipPath(h.points);
            };
            const onMouseUp = async () => {
              if (!isDraggingRegion) return;
              isDraggingRegion = false;
              document.removeEventListener("mousemove", onMouseMove);
              document.removeEventListener("mouseup", onMouseUp);
              if (wasDragging) {
                await this.saveCurrentProfile();
              }
            };
            document.addEventListener("mousemove", onMouseMove);
            document.addEventListener("mouseup", onMouseUp);
          });
        }
      }
    });
  }
  /**
   * Reads content from a file, respecting subpaths (headings/blocks).
   */
  async readSubpathContent(file, path) {
    var _a, _b;
    const content = await this.app.vault.read(file);
    const subpath = path.split("#")[1];
    if (!subpath) return content;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache) return content;
    if (subpath.startsWith("^")) {
      const blockId = subpath.substring(1);
      const block = (_a = cache.blocks) == null ? void 0 : _a[blockId];
      if (block) {
        const lines = content.split("\n");
        return lines.slice(block.position.start.line, block.position.end.line + 1).join("\n");
      }
    }
    const heading = (_b = cache.headings) == null ? void 0 : _b.find((h) => h.heading === subpath);
    if (heading) {
      const startLine = heading.position.start.line;
      let endLine = content.split("\n").length;
      for (const h of cache.headings || []) {
        if (h.position.start.line > startLine && h.level <= heading.level) {
          endLine = h.position.start.line;
          break;
        }
      }
      const lines = content.split("\n");
      return lines.slice(startLine, endLine).join("\n");
    }
    return content;
  }
  /**
   * Samples the average color of the image region under a hotspot.
   * Used for auto-coloring the file list panel.
   */
  sampleRegionColor(h) {
    var _a;
    if (!this.colorCtx || !this.colorCanvas || !((_a = h.points) == null ? void 0 : _a.length)) return null;
    const cw = this.colorCanvas.width;
    const ch = this.colorCanvas.height;
    const [cx, cy] = centroid(h.points);
    const samplePts = [[cx, cy]];
    const step = Math.max(1, Math.floor(h.points.length / 8));
    for (let i = 0; i < h.points.length; i += step) {
      const p = h.points[i];
      samplePts.push([(cx + p[0]) / 2, (cy + p[1]) / 2]);
    }
    let rTotal = 0, gTotal = 0, bTotal = 0, count = 0;
    for (const [px, py] of samplePts) {
      const x = Math.round(px / 100 * cw);
      const y = Math.round(py / 100 * ch);
      if (x < 0 || x >= cw || y < 0 || y >= ch) continue;
      try {
        const pixel = this.colorCtx.getImageData(x, y, 1, 1).data;
        rTotal += pixel[0];
        gTotal += pixel[1];
        bTotal += pixel[2];
        count++;
      } catch (_) {
        continue;
      }
    }
    if (count === 0) return null;
    const darken = 0.6;
    const r = Math.round(rTotal / count * darken);
    const g = Math.round(gTotal / count * darken);
    const b = Math.round(bTotal / count * darken);
    return `rgb(${r}, ${g}, ${b})`;
  }
  /**
   * Opens a modal to edit a hotspot's properties (name, link, embed).
   */
  regionModal(h) {
    const m = document.body.createDiv({ cls: "hotspot-modal zone-detail-panel" });
    m.style.zIndex = "10000";
    m.createDiv({ cls: "panel-header" }).createEl("h2", { text: "Region Link" });
    const c = m.createDiv({ cls: "panel-file-list", attr: { style: "padding:20px" } });
    c.createEl("label", { text: "Region Name", attr: { style: "display:block" } });
    const nameIn = c.createEl("input", { attr: { type: "text", value: h.name } });
    c.createEl("label", { text: "Vault Path (folder or file)", attr: { style: "margin-top:10px;display:block" } });
    const pathIn = c.createEl("input", { attr: { type: "text", value: h.path } });
    new PathSuggest(this.app, pathIn);
    const embedDiv = c.createDiv({ attr: { style: "margin-top:15px;display:flex;align-items:center;gap:10px" } });
    embedDiv.createEl("label", { text: "Embed/Preview in Map", attr: { style: "font-weight:bold;font-size:12px" } });
    const embedToggle = embedDiv.createEl("input", { attr: { type: "checkbox" } });
    embedToggle.checked = h.embed || false;
    const row = c.createDiv({ attr: { style: "margin-top:20px;display:flex;gap:10px" } });
    row.createEl("button", { text: "Save", cls: "mod-cta" }).onclick = async () => {
      h.name = nameIn.value;
      h.path = pathIn.value;
      h.embed = embedToggle.checked;
      await this.saveCurrentProfile();
      m.remove();
      this.render();
    };
    row.createEl("button", { text: "Cancel" }).onclick = () => m.remove();
  }
  /**
   * Displays the file list panel for a hotspot.
   * Handles navigation within folders and sorting.
   */
  showFiles(h, curPath) {
    const rawPath = curPath || h.path;
    if (!rawPath) {
      new import_obsidian4.Notice("No path linked to this region");
      return;
    }
    const [filePath, subpath] = rawPath.split("#", 2);
    const path = filePath;
    const af = this.app.vault.getAbstractFileByPath(path);
    if (af instanceof import_obsidian4.TFile) {
      const leaf = this.app.workspace.getLeaf("tab");
      leaf.openFile(af, subpath ? { eState: { subpath: "#" + subpath } } : void 0);
      return;
    }
    if (!af) {
      this.app.workspace.openLinkText(rawPath, "", true);
      return;
    }
    const root = this.containerEl.children[1];
    let panel = root.querySelector(".zone-detail-panel");
    if (panel && !curPath) {
      panel.remove();
      panel = null;
    }
    if (!panel) {
      panel = root.createDiv({ cls: "zone-detail-panel" });
      let panelBg = "";
      const pcSetting = this.plugin.settings.panelColor.trim().toLowerCase();
      if (pcSetting === "auto") {
        panelBg = this.sampleRegionColor(h) || "";
      } else if (pcSetting) {
        panelBg = pcSetting;
      }
      if (panelBg) {
        panel.style.background = panelBg;
        panel.style.borderColor = panelBg;
      }
      const head = panel.createDiv({ cls: "panel-header" });
      if (panelBg) head.style.background = panelBg;
      head.createEl("h2", { text: h.name || "Files" });
      const btns = head.createDiv({ cls: "panel-btns" });
      btns.createEl("button", { text: "\u270F\uFE0F" }).onclick = () => {
        panel.remove();
        this.regionModal(h);
      };
      btns.createEl("button", { text: "\u2715" }).onclick = () => panel.remove();
      panel.createDiv({ cls: "panel-file-list" });
    }
    const list = panel.querySelector(".panel-file-list");
    list.empty();
    if (!(af instanceof import_obsidian4.TFolder)) {
      list.createDiv({ text: "Path not found", cls: "empty-msg" });
      return;
    }
    if (curPath && curPath !== h.path) {
      const backBtn = panel.querySelector(".panel-back-btn");
      if (backBtn) backBtn.remove();
      const back = panel.createDiv({ cls: "panel-back-btn" });
      back.setText("\u2B05\uFE0F Back");
      panel.insertBefore(back, panel.querySelector(".panel-file-list"));
      back.onclick = () => {
        const parts = path.split("/");
        parts.pop();
        this.showFiles(h, parts.join("/"));
      };
    } else {
      const existing = panel.querySelector(".panel-back-btn");
      if (existing) existing.remove();
    }
    const sortBar = list.createDiv({ cls: "sort-bar" });
    const sortSelect = sortBar.createEl("select", { cls: "sort-select" });
    Object.keys(SORT_LABELS).forEach((k) => {
      const opt = sortSelect.createEl("option", { text: SORT_LABELS[k], value: k });
      opt.selected = k === this.sortType;
    });
    sortSelect.onchange = () => {
      this.sortType = sortSelect.value;
      this.showFiles(h, path);
    };
    sortBar.createEl("button", { text: this.plugin.settings.showTags ? "\u{1F3F7}\uFE0F Hide" : "\u{1F3F7}\uFE0F Tags" }).onclick = async () => {
      this.plugin.settings.showTags = !this.plugin.settings.showTags;
      await this.plugin.saveSettings();
      this.showFiles(h, path);
    };
    const sorted = [...af.children].sort((a, b) => {
      const aIsFolder = a instanceof import_obsidian4.TFolder ? 0 : 1;
      const bIsFolder = b instanceof import_obsidian4.TFolder ? 0 : 1;
      if (aIsFolder !== bIsFolder) return aIsFolder - bIsFolder;
      switch (this.sortType) {
        case "name-az":
          return a.name.localeCompare(b.name);
        case "name-za":
          return b.name.localeCompare(a.name);
        case "mtime-new":
          return (b instanceof import_obsidian4.TFile ? b.stat.mtime : 0) - (a instanceof import_obsidian4.TFile ? a.stat.mtime : 0);
        case "mtime-old":
          return (a instanceof import_obsidian4.TFile ? a.stat.mtime : 0) - (b instanceof import_obsidian4.TFile ? b.stat.mtime : 0);
        case "ctime-new":
          return (b instanceof import_obsidian4.TFile ? b.stat.ctime : 0) - (a instanceof import_obsidian4.TFile ? a.stat.ctime : 0);
        case "ctime-old":
          return (a instanceof import_obsidian4.TFile ? a.stat.ctime : 0) - (b instanceof import_obsidian4.TFile ? b.stat.ctime : 0);
        default:
          return a.name.localeCompare(b.name);
      }
    });
    sorted.forEach((child) => {
      const item = list.createDiv({ cls: "file-item" });
      item.createSpan({ text: (child instanceof import_obsidian4.TFolder ? "\u{1F4C1} " : "\u{1F4C4} ") + child.name });
      if (this.plugin.settings.showTags && child instanceof import_obsidian4.TFile) {
        const tags = getAllTags(this.app, child);
        if (tags.length) {
          const tc = item.createDiv({ cls: "tag-container" });
          tags.forEach((t) => tc.createSpan({ text: t, cls: "tag-chip" }));
        }
      }
      item.onclick = () => {
        if (child instanceof import_obsidian4.TFolder) this.showFiles(h, child.path);
        else if (child instanceof import_obsidian4.TFile) this.app.workspace.getLeaf("tab").openFile(child);
      };
    });
  }
};

// src/SettingsTab.ts
var import_obsidian5 = require("obsidian");
var MeloSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl: c } = this;
    c.empty();
    c.createEl("h2", { text: "Melo View Settings" });
    new import_obsidian5.Setting(c).setName("Default Profile").setDesc("Automatically load this profile when opening Melo View.").addDropdown((d) => {
      const files = new ProfileManager(this.app, this.plugin).getProfileFiles();
      files.sort((a, b) => a.path.localeCompare(b.path));
      d.addOption("", "None");
      files.forEach((f) => d.addOption(f.path, f.basename));
      d.setValue(this.plugin.settings.defaultProfilePath);
      d.onChange(async (v) => {
        this.plugin.settings.defaultProfilePath = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian5.Setting(c).setName("Maps Folder").setDesc("Default folder to save new Melo Maps.").addText(
      (t) => t.setValue(this.plugin.settings.mapsFolder).onChange(async (v) => {
        this.plugin.settings.mapsFolder = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(c).setName("Enable HUD").setDesc("Show a card with file details when hovering over a region.").addToggle(
      (t) => t.setValue(this.plugin.settings.enableHUD).onChange(async (v) => {
        this.plugin.settings.enableHUD = v;
        await this.plugin.saveSettings();
        this.refreshViews();
      })
    );
    new import_obsidian5.Setting(c).setName("Label Style").setDesc("What to show on region labels").addDropdown(
      (d) => d.addOption("name", "Name").addOption("path", "Path").addOption("both", "Both").setValue(this.plugin.settings.displayLabelType).onChange(async (v) => {
        this.plugin.settings.displayLabelType = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(c).setName("Default Hover Label Style").setDesc("Default visual style for new profiles. Can be changed per profile.").addDropdown(
      (d) => d.addOption("default", "Default (Yellow)").addOption("glass", "Glass").addOption("neon", "Neon").addOption("minimal", "Minimal").addOption("comic", "Comic").addOption("scale", "Scale (Big Text)").addOption("fantasy", "Fantasy").setValue(this.plugin.settings.defaultHoverLabelStyle).onChange(async (v) => {
        this.plugin.settings.defaultHoverLabelStyle = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(c).setName("Show Tags").addToggle(
      (t) => t.setValue(this.plugin.settings.showTags).onChange(async (v) => {
        this.plugin.settings.showTags = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(c).setName("Always Show Labels").setDesc("Show labels permanently with a subtle style, clearer on hover").addToggle(
      (t) => t.setValue(this.plugin.settings.alwaysShowLabels).onChange(async (v) => {
        this.plugin.settings.alwaysShowLabels = v;
        await this.plugin.saveSettings();
        this.refreshViews();
      })
    );
    new import_obsidian5.Setting(c).setName("Hover Effect").setDesc("Visual feedback when hovering a region").addDropdown(
      (d) => d.addOption("none", "None (native)").addOption("subtle", "Subtle").addOption("high", "High").setValue(this.plugin.settings.hoverEffectType).onChange(async (v) => {
        this.plugin.settings.hoverEffectType = v;
        await this.plugin.saveSettings();
        this.refreshViews();
      })
    );
    let colorMode = "default";
    if (this.plugin.settings.panelColor === "auto") colorMode = "auto";
    else if (this.plugin.settings.panelColor) colorMode = "custom";
    new import_obsidian5.Setting(c).setName("Panel Background Color").setDesc("Choose how the file list panel background is colored.").addDropdown(
      (d) => d.addOption("default", "Default").addOption("auto", "Auto-detect").addOption("custom", "Color Code").setValue(colorMode).onChange(async (v) => {
        if (v === "default") {
          this.plugin.settings.panelColor = "";
        } else if (v === "auto") {
          this.plugin.settings.panelColor = "auto";
        } else {
          this.plugin.settings.panelColor = "#000000";
        }
        await this.plugin.saveSettings();
        this.display();
        this.refreshViews();
      })
    );
    if (colorMode === "custom") {
      new import_obsidian5.Setting(c).setName("Custom Color").addColorPicker(
        (cp) => cp.setValue(this.plugin.settings.panelColor).onChange(async (v) => {
          this.plugin.settings.panelColor = v;
          await this.plugin.saveSettings();
          this.refreshViews();
        })
      );
    }
    c.createEl("h3", { text: "Import Profile" });
    c.createDiv({ text: "Import an existing Melo Map profile from a Markdown file.", attr: { style: "margin-bottom: 15px; color: var(--text-muted);" } });
    new import_obsidian5.Setting(c).setName("Import Profile").setDesc("Select a Markdown file containing a Melo Map profile.").addButton(
      (b) => b.setButtonText("Import").setCta().onClick(() => {
        new ImportProfileModal(this.app, this.plugin, () => this.display()).open();
      })
    );
  }
  /**
   * Refreshes all active Melo Views to apply setting changes immediately.
   */
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((leaf) => {
      if (leaf.view instanceof MeloView) leaf.view.render();
    });
  }
};

// main.ts
var MeloPlugin = class extends import_obsidian6.Plugin {
  /**
   * Called when the plugin is loaded by Obsidian.
   */
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new MeloView(leaf, this));
    this.addRibbonIcon("map", "Open Melo View", () => this.activateView());
    this.addCommand({
      id: "open-melo-view",
      name: "Open Melo View",
      callback: () => this.activateView()
    });
    this.addSettingTab(new MeloSettingTab(this.app, this));
  }
  /**
   * Loads settings from disk, merging with defaults.
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * Saves current settings to disk.
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Activates the Melo View.
   * If the view is already open, reveals it. Otherwise, creates a new leaf.
   */
  async activateView() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      leaf = this.app.workspace.getLeaf("tab");
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    this.app.workspace.revealLeaf(leaf);
  }
};
